spring.application.name=eLibraryApp-Dev
server.port=8080

# Thymeleaf cache off during development
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Logging
logging.level.com.example.elibrary=DEBUG
