services:
  web: 
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: mysql
    # depends_on: 
    # - db
#   db:
#     image: dhi.io/mariadb:12-debian-dev
#     restart: always
#     ports:
#       - 3306:3306
#     environment:
#       MARIADB_ROOT_PASSWORD: password
#     volumes:
#       - volume_db:/var/lib/mysql
# volumes:
#   volume_db:


