apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"

        - key: "karpenter.sh/disrupted"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: spring
          image: docker.io/tuguldurdev/spring-boot:latest
          ports:
            - containerPort: 8080