spring.application.name=elibrarywebapp0

server.port=8080

spring.datasource.url=jdbc:sqlite:elibrary.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect